DROP TABLE IF EXISTS metals CASCADE;

CREATE TABLE metals (
    site_code VARCHAR,
    map_location VARCHAR,
    region VARCHAR,
    location_name VARCHAR,
    latitude REAL,
    longitude REAL,
    sample_date DATE,
    datetime VARCHAR,
    aluminum REAL,
    antimony REAL,
    arsenic REAL,
    barium REAL,
    beryllium REAL,
    cadmium REAL,
    chromium REAL,
    cobalt REAL,
    copper REAL,
    iron REAL,
    lead REAL,
    manganese REAL,
    mercury REAL,
    molybdenum REAL,
    nickel REAL,
    selenium REAL,
    silver REAL,
    strontium REAL,
    thallium REAL,
    tin REAL,
    titanium REAL,
    vanadium REAL,
    zinc REAL,
    aluminum_rangeval REAL,
    antimony_rangeval REAL,
    arsenic_rangeval REAL,
    barium_rangeval REAL,
    beryllium_rangeval REAL,
    cadmium_rangeval REAL,
    chromium_rangeval REAL,
    cobalt_rangeval REAL,
    copper_rangeval REAL,
    iron_rangeval REAL,
    lead_rangeval REAL,
    manganese_rangeval REAL,
    mercury_rangeval REAL,
    molybdenum_rangeval REAL,
    nickel_rangeval REAL,
    selenium_rangeval REAL,
    silver_rangeval REAL,
    strontium_rangeval REAL,
    thallium_rangeval REAL,
    tin_rangeval REAL,
    titanium_rangeval REAL,
    vanadium_rangeval REAL,
    zinc_rangeval REAL,
    total_metal_count REAL);

\COPY metals from 'metals.csv' WITH (FORMAT csv, HEADER TRUE);

ALTER TABLE metals 
    ADD COLUMN id SERIAL PRIMARY KEY,
    DROP COLUMN region,
    DROP COLUMN location_name,
    DROP COLUMN latitude,
    DROP COLUMN longitude,
    DROP COLUMN datetime,
    DROP COLUMN total_metal_count;
