DROP TABLE IF EXISTS wastewater_compounds;
CREATE TABLE wastewater_compounds (
    "beta-Stigmastanol" REAL,
    "Isopropylbenzene Qualifier" VARCHAR,
    "Isoborneol Qualifier" VARCHAR,
    "N,N-diethyl-meta-toluamide (DEET)" REAL,
    "Cholesterol Qualifier" VARCHAR,
    "Naphthalene Qualifier" VARCHAR,
    "Diethyhexylphthalate Qualifier" VARCHAR,
    "Prometon Qualifier" VARCHAR,
    "Bromacil Qualifier" VARCHAR,
    "Isophorone" REAL,
    "Diazinon" REAL,
    "Tributyl phosphate (TBP) Qualifier" VARCHAR,
    "Isoquinoline" REAL,
    "Isoquinoline Qualifier" VARCHAR,
    "Tris (2-chloro-ethyl) phosphate (TCEP)" REAL,
    "Nonylphenol mono_ethoxylate (NP1EO) Qualifier" VARCHAR,
    site_code VARCHAR,
    "Tris (2-chloro-ethyl) phosphate (TCEP) Qualifier" VARCHAR,
    region VARCHAR,
    "para-Nonylphenol" REAL,
    "Octylphenol diethoxylate (OP2EO)" REAL,
    "4-Cumylphenol" REAL,
    "Cholesterol" REAL,
    "Diazinon Qualifier" VARCHAR,
    "Anthra_quinone" REAL,
    "Benzophenone" REAL,
    "Isoborneol" REAL,
    "Diethylphthalate" REAL,
    "4-n-Octylphenol" REAL,
    "Tris (2-butoxy-ethyl) phosphate (TBEP) Qualifier" VARCHAR,
    "N,N-diethyl-meta-toluamide (DEET) Qualifier" VARCHAR,
    "Anthracene" REAL,
    "Octylphenol mono_ethoxylate (OP1EO) Qualifier" VARCHAR,
    "2,6-Dimethylnaphthalene Qualifier" VARCHAR,
    "Menthol" REAL,
    "Bisphenol A" REAL,
    "4-tert-Octylphenol" REAL,
    "Octylphenol mono_ethoxylate (OP1EO)" REAL,
    "para-Cresol" REAL,
    "1-Methylnaphthalene" REAL,
    "Sample time" REAL,
    "Octylphenol diethoxylate (OP2EO) Qualifier" VARCHAR,
    "Atrazine" REAL,
    "Prometon" REAL,
    "Benzophenone Qualifier" VARCHAR,
    "para-Cresol Qualifier" VARCHAR,
    "2,6-Dimethylnaphthalene" REAL,
    "2-Methylnaphthalene Qualifier" VARCHAR,
    "Carbazole Qualifier" VARCHAR,
    "Metolachlor" REAL,
    "Triclosan" REAL,
    "Naphthalene" REAL,
    "Pyrene" REAL,
    "d-Limonene Qualifier" VARCHAR,
    "Fluoranthene Qualifier" VARCHAR,
    "Isopropylbenzene" REAL,
    "Nonylphenol mono_ethoxylate (NP1EO)" REAL,
    "Map location number" REAL,
    "Acetophenone Qualifier" VARCHAR,
    "Benzo[a]pyrene" REAL,
    "3-tert-butyl-4-hydroxyanisole Qualifier" VARCHAR,
    "4-n-Octylphenol Qualifier" VARCHAR,
    "Diethyhexylphthalate" REAL,
    "d-Limonene" REAL,
    "4-tert-Octylphenol Qualifier" VARCHAR,
    "Triclosan Qualifier" VARCHAR,
    "Galaxolide (HHCB)" REAL,
    "Indole" REAL,
    "Menthol Qualifier" VARCHAR,
    "Tonalide (AHTN)" REAL,
    "Carbazole" REAL,
    "Fluoranthene" REAL,
    "1,4- Dichlorobenzene Qualifier" VARCHAR,
    "Nonylphenol diethoxylate (NP2EO) Qualifier" VARCHAR,
    "Anthra_quinone Qualifier" VARCHAR,
    "Phenol" REAL,
    "Bisphenol A Qualifier" VARCHAR,
    "para-Nonylphenol Qualifier" VARCHAR,
    "Nonylphenol diethoxylate (NP2EO)" REAL,
    "Phenol Qualifier" VARCHAR,
    "Tris (dichloro-isopropyl) phosphate (TDCP)" REAL,
    "Tonalide (AHTN) Qualifier" VARCHAR,
    "beta-Sitosterol" REAL,
    "beta-Sitosterol Qualifier" VARCHAR,
    "Camphor Qualifier" VARCHAR,
    "Diethylphthalate Qualifier" VARCHAR,
    "3-methyl-1h-Indole Qualifier" VARCHAR,
    "Acetophenone" REAL,
    "Bromacil" REAL,
    "3-methyl-1h-Indole" REAL,
    "Tetrabromodiphenyl ether Qualifier" VARCHAR,
    "Triphenyl phosphate (TPP)" REAL,
    "1-Methylnaphthalene Qualifier" VARCHAR,
    "Benzo[a]pyrene Qualifier" VARCHAR,
    "Isophorone Qualifier" VARCHAR,
    "2-Methylnaphthalene" REAL,
    "Tributyl phosphate (TBP)" REAL,
    "Phenanthrene Qualifier" VARCHAR,
    "Pyrene Qualifier" VARCHAR,
    "Tris (dichloro-isopropyl) phosphate (TDCP) Qualifier" VARCHAR,
    "Chlorpyrifos" REAL,
    "Metolachlor Qualifier" VARCHAR,
    "Galaxolide (HHCB) Qualifier" VARCHAR,
    "4-Cumylphenol Qualifier" VARCHAR,
    "Chlorpyrifos Qualifier" VARCHAR,
    "3-beta-Coprostanol Qualifier" VARCHAR,
    "Indole Qualifier" VARCHAR,
    "Tris (2-butoxy-ethyl) phosphate (TBEP)" REAL,
    "3-beta-Coprostanol" REAL,
    "Phenanthrene" REAL,
    "beta-Stigmastanol Qualifier" VARCHAR,
    "Sample date" VARCHAR,
    "Tetrabromodiphenyl ether" REAL,
    "Camphor" REAL,
    "Anthracene Qualifier" VARCHAR,
    "Triphenyl phosphate (TPP) Qualifier" VARCHAR,
    "1,4- Dichlorobenzene" REAL,
    "3-tert-butyl-4-hydroxyanisole" REAL,
    "Atrazine Qualifier" VARCHAR);

\copy wastewater_compounds FROM 'wastewater_compounds.txt' WITH (FORMAT csv, DELIMITER '	', HEADER true);

ALTER TABLE wastewater_compounds 
    ADD COLUMN id SERIAL PRIMARY KEY;
